Creating translator without default category.
yiisoft/translator pull request #33
Opened 2021-01-24 15:58 UTC by darkdef

| Q             | A
| ------------- | ---
| Is bugfix?    | ❌
| New feature?  | ✔️
| Breaks BC?    | ✔️

For usage without fake Category on create instance (for example - in modules)
see:
https://github.com/yii-extension/user-translations/blob/edc30bcc269728ee9b7ba2e5777cbc2c2fc943c5/config/common/yiisoft-translator.php#L53

2021-01-24 23:41 UTC, samdark commented on src/Translator.php
> +    private string $defaultCategory = '';
I wonder if we need default category at all. There was no ability to skip category in Yii 2. The downside if that in some cases you have to repeat yourself. The pro is that message extraction and overall logic becomes a bit simpler.

2021-01-25 18:03 UTC, samdark requested changes

2021-01-25 18:03 UTC, samdark commented on src/Translator.php
> +        ?CategorySource $defaultCategory = null,
```suggestion
        string $defaultCategory = 'app',
```

2021-01-25 18:12 UTC, darkdef commented on src/Translator.php
> +        ?CategorySource $defaultCategory = null,
Or without categorySource and usage defaultCategoryName, or with CategorySource(name, reader, formatter etc)

2021-01-25 18:17 UTC, samdark commented on src/Translator.php
> +        ?CategorySource $defaultCategory = null,
Or we can remove it altogether.

2021-01-25 18:31 UTC, darkdef commented on src/Translator.php
> +        ?CategorySource $defaultCategory = null,
yep

2021-01-25 19:03 UTC, samdark approved these changes

2021-01-25 19:03 UTC, merged