Make message formatter in category source optional + Increase MSI to 100%
yiisoft/translator pull request #76
Opened 2022-10-17 18:46 UTC by vjik

| Q             | A
| ------------- | ---
| Is bugfix?    | ❌
| New feature?  | ✔️
| Breaks BC?    | ❌
| Fixed issues  | -

2022-10-17 18:54 UTC, darkdef commented on tests/TranslatorTest.php
> +            $translator->translate('hello', ['name' => 'Kitty'], 'withFormatter')
Why result of "with formatter" contain formatted text?

2022-10-17 18:56 UTC, vjik commented on tests/TranslatorTest.php
> +            $translator->translate('hello', ['name' => 'Kitty'], 'withFormatter')
> Why result of "with formatter" contain formatted text?

Because in category used `NullMessageFormatter`.

2022-10-18 10:27 UTC, vjik commented on tests/TranslatorTest.php
> +            $translator->translate('hello', ['name' => 'Kitty'], 'withFormatter')
Improved test

2022-10-18 10:52 UTC, darkdef approved these changes

2022-10-18 11:32 UTC, arogachev commented on src/Translator.php
> +        return end($this->categorySources[$category])->format(
(Optional, code style) Separate variable for `$categorySource` is better in my opinion in terms of code readability.

2022-10-18 11:36 UTC, arogachev commented on tests/CategoryTest.php
> +        string $expectedMessage,
(Optional) Maybe swap places for the first two arguments? It's more natural for me to see "before" state first, then "after" state.

2022-10-18 11:37 UTC, arogachev commented on tests/SimpleMessageFormatterTest.php
> +    public function testFormatPluralWithMissingKeys2(): void
(Naming) Maybe give more meaningful name?

2022-10-18 11:38 UTC, arogachev commented on tests/SimpleMessageFormatterTest.php
> +    public function testFormatPluralWithMissingKeys2(): void
By the way, it's completely the same as the test without "2" digit. Maybe refactor it? It does not depend on the order. just the count, right?

2022-10-18 11:47 UTC, arogachev commented on tests/TranslatorTest.php
> +        $categorySourceWithFormatter = new CategorySource(
Maybe use data provider?

2022-10-18 11:47 UTC, arogachev requested changes
:+1:

2022-10-18 11:51 UTC, vjik commented on src/Translator.php
> +        return end($this->categorySources[$category])->format(
`end($this->categorySources[$category])` — get last category source. it's good readability for me. This don't use later, I think use variable is overhead.

2022-10-18 11:52 UTC, vjik commented on tests/CategoryTest.php
> +        string $expectedMessage,
In phpunit use before expected value, then actual value: `assertSame(mixed $expected, mixed $actual)`.

2022-10-18 11:55 UTC, arogachev commented on src/Translator.php
> +        return end($this->categorySources[$category])->format(
Sorry, don't agree. But I marked this as optional.

2022-10-18 11:57 UTC, arogachev commented on tests/CategoryTest.php
> +        string $expectedMessage,
Yes, also thought about that, but this is a data provider's data, not assert. Again, it's optional and up to you.

2022-10-18 11:58 UTC, vjik commented on tests/TranslatorTest.php
> +        $categorySourceWithFormatter = new CategorySource(
Done.

2022-10-18 11:58 UTC, vjik commented on tests/SimpleMessageFormatterTest.php
> +    public function testFormatPluralWithMissingKeys2(): void
Refactor to data provider.

2022-10-18 12:29 UTC, arogachev approved these changes

2022-10-18 12:32 UTC, arogachev commented
Is BC break expected?

2022-10-18 12:36 UTC, arogachev commented
> Is BC break expected?

Discussed in group chat - it's OK.

2022-10-18 12:36 UTC, merged