Move `intl` formatter here
yiisoft/translator pull request #78
Opened 2022-10-18 14:28 UTC by vjik

| Q             | A
| ------------- | ---
| Is bugfix?    | ❌
| New feature?  | ✔️
| Breaks BC?    | ❌
| Fixed issues  | -

2022-10-19 11:12 UTC, arogachev commented on .github/workflows/build.yml
> +      extensions: :intl
Shouldn't it be "intl" without ":" prefix? But, moreover, shouldn't this line be removed completely? Or is it a special syntax for excluding extensions? :thinking:

2022-10-19 11:14 UTC, arogachev commented on .github/workflows/build.yml
> +      phpunitConfig: phpunit-with-intl.xml
What's the purpose of it? In validator it works fine without this setting.

2022-10-19 11:21 UTC, arogachev commented on README.md
>  There are two types of additional packages. Message source provide support of various message storage formats such as
After changing headings' structure, this part needs to be adjusted as well. Because message formatters are now built-in and no longer in additional packages.

2022-10-19 11:22 UTC, arogachev commented on README.md
> +- [Simple formatter](docs/en/simple-formatter.md) replace parameters in messages only. Does not take into account the
```suggestion
- [Simple formatter](docs/en/simple-formatter.md) just replaces parameters in messages. Does not take into account the 
```

2022-10-19 11:26 UTC, arogachev commented on phpunit.xml.dist
Other config nodes are not needed, right? For example:

```xml
<coverage>
    <include>
        <directory>./src</directory>
    </include>
</coverage>
```

2022-10-19 11:31 UTC, arogachev commented on tests/envs/WithIntl/IntlMessageFormatterTest.php
> +final class IntlMessageFormatterTest extends TestCase
Since `IntlMessageFormatter` is just a proxy on built-in PHP functionality (or extensions' functionality to be exact), I think testing that a proper method was called correctly is enough, because it's already tested by vendor and we can just rely on that.

2022-10-19 11:34 UTC, arogachev commented on src/IntlMessageFormatter.php
> +                'In order to use intl message formatter intl extension must be installed and enabled.'
```suggestion
                'In order to use intl message formatter, intl extension must be installed and enabled.'
```

2022-10-19 11:45 UTC, arogachev requested changes
:+1:

2022-10-19 11:49 UTC, arogachev commented on CHANGELOG.md
> +- New #78: Add `IntlMessageFormatter` that utilizes PHP intl extension message formatting capabilities (@vjik)
Maybe change the version above to "2.0.0" because of existing BC break? To not forget during release.

2022-10-19 12:50 UTC, vjik commented on .github/workflows/build.yml
> +      extensions: :intl
"is it a special syntax for excluding extensions" — yes (see [docs](https://github.com/shivammathur/setup-php#heavy_plus_sign-php-extension-support)).

By default intl extension available.

2022-10-19 12:51 UTC, vjik commented on .github/workflows/build.yml
> +      phpunitConfig: phpunit-with-intl.xml
See `phpunit-with-intl.xml`. Purpose is test `IntlMessageFormatter`.

2022-10-19 12:57 UTC, vjik commented on README.md
>  There are two types of additional packages. Message source provide support of various message storage formats such as
Message formatters can be in other packages.

2022-10-19 12:57 UTC, vjik commented on phpunit.xml.dist
Why?

2022-10-19 12:58 UTC, vjik commented on tests/envs/WithIntl/IntlMessageFormatterTest.php
> +final class IntlMessageFormatterTest extends TestCase
Tests copied from https://github.com/yiisoft/translator-formatter-intl

2022-10-19 13:00 UTC, vjik commented on src/IntlMessageFormatter.php
> +                'In order to use intl message formatter intl extension must be installed and enabled.'
done

2022-10-19 13:01 UTC, vjik commented on CHANGELOG.md
> +- New #78: Add `IntlMessageFormatter` that utilizes PHP intl extension message formatting capabilities (@vjik)
Yii Dev Tool make this automatically.

2022-10-20 07:57 UTC, arogachev commented on phpunit.xml.dist
You already added it, so it's no longer actual.

2022-10-20 07:59 UTC, arogachev commented on tests/envs/WithIntl/IntlMessageFormatterTest.php
> +final class IntlMessageFormatterTest extends TestCase
OK, if they already existed, let's leave a deletion for further discussion / PR.

2022-10-20 08:00 UTC, arogachev approved these changes

2022-10-20 08:00 UTC, merged