Small refactoring
yiisoft/translator pull request #9
Opened 2020-09-21 09:55 UTC by darkdef

| Q             | A
| ------------- | ---
| Is bugfix?    | ❌
| New feature?  | ❌
| Breaks BC?    | ✔️/❌

2020-09-22 21:28 UTC, samdark commented
@darkdef please update from master.

2020-09-23 18:50 UTC, romkatsu commented on src/Category.php
> +<?php
set strict type please

2020-09-23 18:50 UTC, romkatsu commented on src/Category.php
> +    private $reader;
set type please

2020-10-04 22:21 UTC, samdark requested changes

2020-10-04 22:21 UTC, samdark commented on src/Translator.php
> +            $fallback = $localeObject->fallbackLocale();
Fallback should be done multiple times until translation is either found or not found anywhere. For example, `hy-Latn-IT-arevela` falls back to `hy-Latn-IT` then to `hy-Latn` then to `hy`.

2020-10-04 22:21 UTC, samdark commented on src/Translator.php
> +        if (empty($category) or empty($this->categories[$category])) {
```suggestion
        if (empty($category) || empty($this->categories[$category])) {
```

2020-10-04 22:21 UTC, samdark commented on src/TranslatorInterface.php
> +     * @param string $locale the target locale
```suggestion
     * @param string|null $category the message category
     * @param string|null $locale the target locale
```

2020-10-04 22:22 UTC, samdark commented on src/Translator.php
> +            $fallback = $localeObject->fallbackLocale();
A test should be implemented for this case.

2020-10-06 17:01 UTC, darkdef commented on src/Translator.php
> +        if (empty($category) or empty($this->categories[$category])) {
fixed

2020-10-06 17:01 UTC, darkdef commented on src/TranslatorInterface.php
> +     * @param string $locale the target locale
fixed

2020-10-06 17:02 UTC, darkdef commented on src/Translator.php
> +            $fallback = $localeObject->fallbackLocale();
Tests added

2020-10-06 22:40 UTC, samdark approved these changes

2020-10-06 22:40 UTC, merged

2020-10-06 22:40 UTC, samdark commented
Thank you! 👍