Simplify category sources config
yiisoft/translator pull request #90
Opened 2022-11-04 11:41 UTC by rustamwin

| Q             | A
| ------------- | ---
| Is bugfix?    | ❌
| New feature?  | ✔️/❌
| Breaks BC?    | ✔️/❌
| Fixed issues  | Support upcoming release of `yiisoft/definitions`

2022-11-05 10:43 UTC, vjik requested changes
Need test

2022-11-05 15:15 UTC, vjik commented on config/common.php
> +    //    'definition' => static function (Aliases $aliases, MessageFormatterInterface $messageFormatter) use ($params) {
1) `MessageFormatterInterface` don't should defined in container in base cases. 
2) `Aliases` can be don't used in application. Suggest don't use additional dependencies in example.

2022-11-05 15:15 UTC, vjik commented on config/common.php
> +    //        return new CategorySource(
Suggest use FQN for ability copy/paste example.

2022-11-07 08:53 UTC, rustamwin commented
> Need test

Added

2022-11-07 12:00 UTC, vjik approved these changes

2022-11-07 19:03 UTC, samdark approved these changes

2022-11-07 19:05 UTC, merged