Add `getMessages` method to `CategorySource`
yiisoft/translator pull request #94
Opened 2022-11-20 19:22 UTC by xepozz

| Q             | A
| ------------- | ---
| Is bugfix?    | ❌
| New feature?  | ✔️
| Breaks BC?    | ❌

Due to `reader` has `getMessages` method it may be helpful to use it with CategorySource, for example, when you want to export all message to external service.

2022-11-20 19:24 UTC, samdark approved these changes
Need changelog.

2022-11-20 20:07 UTC, vjik requested changes

2022-11-20 20:07 UTC, vjik commented on CHANGELOG.md
> +- New #94: Add `getMessages` method to `CategorySource` (@xepozz)
```suggestion
- New #94: Add `getMessages()` method to `CategorySource` (@xepozz)
```

2022-11-20 20:07 UTC, vjik commented on src/CategorySource.php
> +     */
```suggestion
     *
     * @see MessageReaderInterface::getMessages()
     */
```

2022-11-20 20:07 UTC, vjik commented on src/CategorySource.php
> +    public function getMessages(string $locale): array
Need test

2022-11-23 06:24 UTC, vjik approved these changes

2022-11-24 18:50 UTC, merged