Add write method to category source
yiisoft/translator pull request #95
Opened 2022-11-20 19:50 UTC by xepozz

| Q             | A
| ------------- | ---
| Is bugfix?    | ❌
| New feature?  | ✔️
| Breaks BC?    | ✔️

2022-11-20 20:04 UTC, vjik requested changes

2022-11-20 20:04 UTC, vjik commented on src/CategorySource.php
> +        private MessageWriterInterface $writer,
It's should be optional.

2022-11-23 06:33 UTC, vjik requested changes

2022-11-23 06:33 UTC, vjik commented on CHANGELOG.md
> +- New #95: Add `write` method to `CategorySource` (@xepozz)
```suggestion
- New #95: Add `write()` method to `CategorySource` (@xepozz)
```

2022-11-23 06:33 UTC, vjik commented on src/UnwritableCategorySourceException.php
> +    }
```suggestion
    public function __construct(string $categoryName)
    {
        parent::__construct(sprintf('Unable to write into category with name "%s".', $categoryName));
    }
```

2022-11-23 06:33 UTC, vjik commented on src/CategorySource.php
> +    public function write(array $messages, string $locale): void
In `MessageWriterInterface::write` order of arguments: locale, messages.
Here: messages, locale.

It's inconsistent. Suggest use same order.

2022-11-23 06:33 UTC, vjik commented on src/UnwritableCategorySourceException.php
> +        parent::__construct(sprintf('Unable to write into category with name "%s".', $categoryName), 0, $previous);
Confused message `Unable to write into category with name...`. It's can mean write error. Suggest use message similar to `Category "%s" don't support write messages.`.

2022-11-24 19:17 UTC, xepozz commented on src/UnwritableCategorySourceException.php
> +    }
it's bad to deny chaining exception

2022-11-26 19:14 UTC, samdark approved these changes

2022-11-27 04:44 UTC, rustamwin approved these changes

2022-11-27 04:44 UTC, rustamwin commented on src/CategorySource.php
> +        private null|MessageWriterInterface $writer = null,
```suggestion
        private ?MessageWriterInterface $writer = null,
```

2022-11-27 07:55 UTC, vjik commented on src/UnwritableCategorySourceException.php
> +    }
I'm agree. But `UnwritableCategorySourceException` throws into `CategorySource` only and never use previous exception. Throw ` `UnwritableCategorySourceException` in userland not supposed to.

2022-11-27 10:12 UTC, xepozz commented on src/UnwritableCategorySourceException.php
> +    }
It may be thrown in any `MessageReaderInterface` implementations

2022-11-27 10:25 UTC, vjik commented on src/UnwritableCategorySourceException.php
> +    }
> It may be thrown in any `MessageReaderInterface` implementations

No. It's used in final `CategorySource` class.

Implementations of `MessageReaderInterface` don't use this exception.

2022-11-27 12:50 UTC, xepozz commented on src/UnwritableCategorySourceException.php
> +    }
It's true only about `yiisoft` implementations of `MessageReaderInterface`.
I may create a aggregated `MessageReader` and work with several `CategorySource` at the time and manipulate with theirs' behaviours.
I don't see any reasons for removing these arguments even if they are not used in that particular case.

2022-11-27 16:14 UTC, vjik approved these changes

2022-11-27 16:23 UTC, merged